# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "policyengine-unstable-${version}";
  version = "2019-03-19";
  rev = "967c7e4df741ac2a85becfb67d281bffdf83f317";

  goPackagePath = "github.com/deptofdefense/policyengine";
  subPackages = ["cmd"];

  src = fetchgit {
    inherit rev;
    url = "git@github.com:deptofdefense/policyengine";
    sha256 = "1mlabihlb30953rxa384phb91n0s81naiw4cmp5c4fcc84hkimln";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
