# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "policyengine-unstable-${version}";
  version = "2019-03-19";
  rev = "9300614921d1dc80af61bf0c8d77c2db627a46bb";

  goPackagePath = "github.com/deptofdefense/policyengine";
  subPackages = ["cmd"];

  src = fetchgit {
    inherit rev;
    url = "https://github.com/deptofdefense/policyengine";
    sha256 = "0skv3y7j1jnxvhq40i07nn516s1gpwq9z5syld4c9dr9q7m65syk";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
