# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/spf13/cobra";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cobra";
      rev = "ba1052d4cbce7aac421a96de820558f75199ccbc";
      sha256 = "05q5m1dp2lb0jcba5mrk5s3scnsvyalzgagm54b6prcfsxpkw34y";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "24fa6976df40757dce6aea913e7b81ade90530e1";
      sha256 = "0rf6prz6gl0l1b3wijzdgq887cdwigvzxvz6gqbm5l8pkq3fx1m9";
    };
  }
  {
    goPackagePath = "pault.ag/go/fasc";
    fetch = {
      type = "git";
      url = "https://github.com/paultag/go-fasc";
      rev = "38e8cd7ca983d5534b90c3d2da9db49a812970de";
      sha256 = "15vvz2snfhcg4jjacjghp6kjgp31wmbxp1zz12d6jhqh0g3p2cbx";
    };
  }
  {
    goPackagePath = "pault.ag/go/othername";
    fetch = {
      type = "git";
      url = "https://github.com/paultag/go-othername";
      rev = "859caba4369b4a71f175bc89f2b48d0672f44b32";
      sha256 = "14c9zvbip3r4mfdyj0lwml8isv00r5pkyl97qg1dldpza0p3fpi0";
    };
  }
  {
    goPackagePath = "pault.ag/go/piv";
    fetch = {
      type = "git";
      url = "https://github.com/paultag/go-piv";
      rev = "826e579a4a1e58143091c98f5e9d51fee611cd08";
      sha256 = "172ac62wq75q9y53qryc8kld5qdzbxx4q6rylpgj199i8fg6yr46";
    };
  }
]
