# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "opa-unstable-${version}";
  version = "2019-02-25";
  rev = "8b08af7f8aa407f4c8f371c97dc861df58ed04b1";

  goPackagePath = "github.com/open-policy-agent/opa";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/open-policy-agent/opa";
    sha256 = "1kllvmaxf2mml8d3r5qkfcrjim7vk4k6nn7r00f2l9sw4kzh0a3p";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
