# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "traefik-unstable-${version}";
  version = "2019-02-11";
  rev = "443902a0f01da4cb844bcc8421816f105e4894dc";

  goPackagePath = "github.com/containous/traefik";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/containous/traefik";
    sha256 = "0lncygkqws5jvbhpx2qlr18y8b325y9a6690ll9azlphxydrv44m";
  };
  preConfig = ''
    go generate
  '';

  patches = [ ./reorderMiddleware.patch];
  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
